### ISSUE TITLE
Remove duplicate Theme Object page

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/DNNDocs#352]
## Description of bug
When searching for "Theme Object" on the site, this page shows up:
https://dnndocs.com/content/guides/tutorials/theme-objects-1/index.html#theme-objects

There is a newer version of this page:
https://dnndocs.com/content/guides/tutorials/theme-objects/index.html

Containing the same list of Theme Objects at the bottom
(which IMO all should have their "own page" in the future, I'll try to work on that)

## Steps to reproduce
Search for "Theme Object" on the DNNDocs.

## Current result
https://dnndocs.com/content/guides/tutorials/theme-objects-1/index.html#theme-objects shows up

## Expected result
IMO it shouldn't

**Comment by david-poindexter** [comment]
@Timo-Breumelhof this file no longer shows up in the search or in the GitHub project.  

It appears, though, the file and/or URL is still accessible and/or cached in the hosting environment.  If it were a permanent redirect to the new file/URL, that would be great.  However, it is still showing up in its original state.  I'll ask @dnndev if he can take a look into this.  Perhaps old files are not being handled during the CI/CD process.

Since this issue is technically resolved, I'll go ahead and close it.  We'll handle the potential issue in the hosting environment and/or CI/CD process separately.

**Comment by Timo-Breumelhof** [comment]
ok, thanks
