### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNNDocs#397]
Can we get a "known issues" section going for upgrades, installs, security alerts and other fun stuff?

Just an idea I put a post in the forum about it.

**Comment by sleupold** [comment]
where? in release notes for DNN Platform releases?

**Comment by thabaum** [comment]
somewhere that can be linked in each release to check is what I am thinking.  I was thinking maybe I need to submit some sort of PR here to show an example.

Upgrade Known Issues.  Of coarse they should be documented somehow in release notes when possible. but this is not a place to look specifically at them for all recent and past releases.

I was thinking maybe dnndocs.com can house the known issues or breaking changes so you have one place to go through and review them all instead of browsing through the releases and release notes.

And the dnn community site and github releases can refer people to this location with community updated known issues that are verified.

**Comment by david-poindexter** [comment]
@thabaum this is a bit of a philosophical and practicality conversation.  Each release of **DNN Platform** (at the time of release) has no **known issues**.  Therefore, nothing can be documented at that time for that release.  (There are at times exceptions to this rule - e.g., in the case of deprecated APIs or major breaking changes).  Issues are reported after-the-fact.  Often, issues can span multiple releases, but these are documented in the **DNN Platform** GitHub repo.  When an issue is resolved, the fix is included in a new release.  Each release of **DNN Platform** has **Release Notes** associated it and those **Release Notes** have all issues resolved listed therein.

So, I am not really clear on the goal of your request or how it would actually be executed or managed.  Can you please provide some clarity if you think this is still a valid and actionable issue for the DNN Docs project?

**Comment by thabaum** [comment]
I suppose what I am after... is a way to find resources for troubleshooting issues and finding out why other things may have happened.   Things on GitHub get buried.

So for example.. i have all these extra persona bar packages... where do I find the solution for removing them since maybe that one install i had an RC installed on it.  So now if I had updated to an RC which is not recommended "Unless in desperate need" and some other issue comes about due to it.  There is no place to get the help I need other than I suppose posting a question and waiting.

Or lets say there is a work around for something that is a bug or a current issue.  The issue can be put on the known issues as one that has been a bug for a long time and what needs to be done to help deal with it in the meantime.  And then that helps build awareness that these issues can use maybe a little more attention if possible.

**Comment by thabaum** [comment]
An example... the purging of log files

**Comment by thabaum** [comment]
https://dnndocs.com/content/guides/tutorials/troubleshooting

I think this is where i was needing directed to, thank you.

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/69001274-5efa5b80-0890-11ea-85cc-7eb9ce9ffd4a.png)
This could use a little description of the troubleshooting section and possibly to reference github for submitting ideas to add to help troubleshooting if something is missing.
