### ISSUE TITLE
Maintaining Modules

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNNDocs#421]
## Description of documentation change
Is your documentation request related to existing documentation or new documentation? Provide a clear and concise description of the requested documentation change.

Discuss things module developers need to consider while creating and maintaining modules.  Information about upcoming releases (Such as Version 11 .NET Core) that helps explain any future transitions and how to prepare and make code adjustments as needed to future proof your modules in simple terms...

## Existing documentation URL (if applicable)
https://github.com/thabaum/DNNDocs/blob/master/content/features/modules/index.md

## Existing documentation section (if applicable)
added to the end of section

## Proposed area for new documentation (if applicable)
Provide the area in which the proposed new documentation should reside.

## Screenshots
If applicable, provide screenshots to help explain your documentation request.

## Additional context
A lot of good stuff gets explained about how Web Forms will be replaced with Razor Pages for the most part and that creating a SPA or MVC module is recommended for the most longest future use as SPA may be the way to go if starting a new project simply because it is how things will most likely be working in the future and MVC or Web Forms maybe retired before SPA.  I am not sure if I am accurate but this type of stuff would be helpful for developers and any good information to help give direction IMO is awesome stuff.

**Comment by david-poindexter** [comment]
@thabaum thank you for creating this issue.  At a high level, this is indeed the plan.  This though is a bit too broad to take any specific action on submitting a pull request.  In the interest of keeping the backlog clean, we'll go ahead and close this issue.  If you have issues that can be more specifically defined, this would go a long way in helping others pick up the issue and submit a pull request.  Otherwise, know that we are in agreement here at a high level.  Thanks again!
