### ISSUE TITLE
Feedback for Menu

### ISSUE THREAD

**Issue by hotovydt** [DNNCommunity/DNNDocs#723]

**Comment by valadas** [comment]
Sooo, first the some of the older manuals where created by corp for older version and are at https://www.dnnsoftware.com/community/download/manuals
They have stopped making those and mainly have nowadays Evoq articles, some make sense for platform and some don't.

dnncommunity.org was created to help document platform and is maintained for free by very few contributors as they have the time to do so. The project is open source and if you can improve anything, please do so. Replacing some of the links that go to dnnsoftware domain with articles here would certainly be a welcome improvement and make those articles more maintainable and potentially improve the search features too.
It uses DocFx, they at some point changed the search indexing for Algolia and since then the search is not great IMO.  There may be some setting to adjust to make it better potentially.
